logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO
    nl.tenmore.recipeserver: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate: WARN

spring:
  application:
    name: recipe-server

  datasource:
    url: jdbc:postgresql://localhost:5432/recipedb
    username: recipe
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/recipe
  web:
    error:
      include-message: never


