apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          args: ["start-dev", "--import-realm"]
          env:
            - name: KC_HOSTNAME
              value: keycloak.local
            - name: KC_HOSTNAME_STRICT
              value: "false"
          volumeMounts:
            - name: realm
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm
          configMap:
            name: keycloak-realm
