CREATE TABLE recipes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    book                VARCHAR(255)                            NOT NULL,
    page_number         INTEGER                                 NOT NULL,
    created_by_username VARCHAR(255)                            NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    pick_state          SMALLINT                                NOT NULL,
    CONSTRAINT pk_recipes PRIMARY KEY (id)
);